"""add ai status to emails

Revision ID: 675f2577754e
Revises: 90efbcbc1453
Create Date: 2026-06-09 16:40:06.365392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675f2577754e'
down_revision: Union[str, Sequence[str], None] = '90efbcbc1453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', 
        sa.Column(
        'ai_status',
        sa.String(length=50),
        nullable=False,
        server_default='pending',
  	  )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'ai_status')
    # ### end Alembic commands ###
